<?php
/**
 * This is the default template part for the
 * instructions in the transaction meta area of
 * the Transaction Confirmation template part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/content-confirmation/details/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_confirmation_before_transaction_instructions' ); ?>
<div class="it-exchange-transaction-instructions">
	<p><?php it_exchange( 'transaction', 'instructions' ); ?></p>
</div>
<?php do_action( 'it_exchange_confirmation_after_transaction_instructions' ); ?>