<?php
/**
 * This is the default template part for the
 * order note in the transaction meta loop of
 * the Transaction Confirmation template part.
 *
 * @since 2.0.0
 * @version 2.0.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/content-confirmation/elements/
 * directory located in your theme.
 */
?>

<?php if ( it_exchange( 'transaction', 'has-note' ) ): ?>
	<?php do_action( 'it_exchange_content_confirmation_before_order_note_element' ); ?>
	<div class="it-exchange-transaction-order-note">
		<span><strong><?php _e( 'Order Note', 'it-l10n-ithemes-exchange' ); ?>:</strong></span>
		<p><?php it_exchange( 'transaction', 'note' ); ?></p>
	</div>
	<?php do_action( 'it_exchange_content_confirmation_before_order_note_element' ); ?>
<?php endif; ?>