<?php
/**
 * Default template part for the product on the
 * transaction confirmation template part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/content-confirmation/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_confirmation_before_product_element' ); ?>
<div class="it-exchange-transaction-product it-exchange-table">
	<div class="it-exchange-transaction-product-details it-exchange-table-row">
		<?php do_action( 'it_exchange_content_confirmation_before_product_featured_image' ); ?>
		<div class="it-exchange-transaction-product-thumbnail-title it-exchange-table-column">
			<div class="it-exchange-table-column-inner">
				<?php do_action( 'it_exchange_content_confirmation_before_product_featured_image' ); ?>
				<?php it_exchange( 'transaction', 'featured-image' ); ?>
				<?php do_action( 'it_exchange_content_confirmation_after_product_featured_image' ); ?>
				
				<?php do_action( 'it_exchange_content_confirmation_after_product_title' ); ?>
				<?php it_exchange( 'transaction', 'product-attribute', array( 'attribute' => 'title', 'wrap' => 'h3' ) ); ?>
				<?php do_action( 'it_exchange_content_confirmation_after_product_title' ); ?>
			</div>
		</div>
		
		<?php do_action( 'it_exchange_content_confirmation_before_product_cart_object' ); ?>
		<div class="it-exchange-transaction-product-cart-object it-exchange-table-column">
			<div class="it-exchange-table-column-inner">
				<?php it_exchange( 'transaction', 'product-attribute', array( 'attribute' => 'product_count' ) ); ?>
				<span class="it-exchange-right"><?php it_exchange( 'transaction', 'product-attribute', array( 'attribute' => 'product_base_price' ) ); ?></span>
			</div>
		</div>
		<?php do_action( 'it_exchange_content_confirmation_after_product_cart_object' ); ?>
	</div>
	
	<?php if ( it_exchange( 'transaction', 'has-product-downloads' ) ) : ?>
		<?php do_action( 'it_exchange_content_confirmation_before_product_downloads' ); ?>
		<div class="it-exchange-transaction-product-downloads it-exchange-table-row">
			<div class="it-exchange-table-column-downloads it-exchange-table-column">
				<div class="it-exchange-table-column-inner">
					<h4><?php _e( 'Downloads', 'LION' ); ?></h4>
					<?php if ( ! it_exchange( 'transaction', 'get-cleared-for-delivery' ) ) : ?>
						<p><?php _e( 'The status for this transaction does not grant access to downloadable files. Once the transaction is updated to an appoved status, you will receive a followup email with your download links.', 'LION' ); ?></p>
					<?php endif; ?>
					<?php while( it_exchange( 'transaction', 'product-downloads' ) ) : ?>
						<div class="it-exchange-transaction-product-download">
							<?php if ( it_exchange( 'transaction', 'has-product-download-hashes' ) ) : ?>
								<ul class="it-exchange-downloads-data">
									<?php while( it_exchange( 'transaction', 'product-download-hashes' ) ) : ?>
										<li class="it-exchange-download-data it-exchange-clearfix">
											<span class="it-exchange-transaction-product-download-title it-exchange-left">
												<?php it_exchange( 'transaction', 'product-download', array( 'attribute' => 'title' ) ); ?>
											</span>
											<?php if ( ! it_exchange( 'transaction', 'get-product-download-hash', array( 'attribute' => 'download-limit' ) ) || it_exchange( 'transaction', 'get-product-download-hash', array( 'attribute' => 'downloads-remaining' ) ) ) : ?>
												<?php if ( it_exchange( 'transaction', 'get-cleared-for-delivery' ) ) : ?>
													<span class="it-exchange-right">
														<a class="button btn" href="<?php it_exchange( 'transaction', 'product-download-hash', array( 'attribute' => 'download-url' ) ); ?>"><?php _e( 'Download', 'LION' ); ?></a>
													</span>
												<?php endif; ?>
											<?php endif; ?>
										</li>
									<?php endwhile; ?>
								</ul>
							<?php endif; ?>
						</div>
					<?php endwhile; ?>
				</div>
			</div>
			<div class="it-exchange-transaction-product-cart-object">
				
			</div>
		</div>
		<?php do_action( 'it_exchange_content_confirmation_after_product_downloads' ); ?>
	<?php endif; ?>
</div>
<?php do_action( 'it_exchange_content_confirmation_after_product_element' ); ?>
