<?php
/**
 * This file contains the markup for the email template foot.
 *
 * @since   2.0.0
 * @link    http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 *
 * Example: theme/exchange/emails/partials/foot.php
 */
?>
</table>
<?php if ( is_customize_preview() ) {
	wp_footer();
} ?>
</body>
</html>
