<?php
/**
 * This file contains the markup for the email template head.
 *
 * @since   2.0.0
 * @link    http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 *
 * Example: theme/exchange/emails/partials/head.php
 */
?>
<!DOCTYPE html>
<html>
<head>
	<title>iThemes Exchange</title>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />

</head>
<body style="
<?php if ( it_exchange( 'email', 'get-layout' ) === 'boxed' || it_exchange( 'email', 'get-footer-background' ) === 'transparent' ): ?>
	<?php it_exchange( 'email', 'background-el-styles' ); ?>
<?php endif; ?>

	margin: 0 !important; padding: 0 !important; font-family: <?php it_exchange( 'email', 'body-font' ); ?>; background-color: <?php it_exchange( 'email', 'body-el-bkg' ); ?>;
	color: <?php it_exchange( 'email', 'body-text-color' ); ?>; font-size: <?php it_exchange( 'email', 'body-font-size' ); ?>px;">

<table border="0" cellpadding="0" cellspacing="0" width="100%" class="main" style="height: 100%;
<?php if ( it_exchange( 'email', 'get-layout' ) === 'full' ): ?>
	<?php it_exchange( 'email', 'background-el-styles' ); ?>
<?php endif; ?>
	">
