<?php
/**
 * This file contains the markup for the email template header.
 *
 * @since   1.36
 * @link    http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 *
 * Example: theme/exchange/emails/partial/header.php
 */
?>
<tr>
	<td align="center">
		<!--[if mso]>
		<center>
			<table>
				<tr>
					<td width="640">
		<![endif]-->
		<table id="header" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 640px; background: <?php it_exchange( 'email', 'header-background' ); ?>; margin: 40px auto 0 auto; <?php echo it_exchange( 'email', 'has-header-image' ) ? 'min-height:225px;' : ''; ?>" class="wrapper">
			<tr>
				<td align="center" valign="top" style="padding: 54px 25px; background-image: url(<?php it_exchange( 'email', 'header-image' ); ?>); background-position: top center; background-repeat: no-repeat; background-size: cover; border-top: 5px solid <?php it_exchange( 'email', 'header-background' ); ?>; border-bottom: 0; border-radius: 5px 5px 0 0;">
					<?php if ( it_exchange( 'email', 'has-header-logo' ) ): ?>
						<img src="<?php it_exchange( 'email', 'header-logo' ); ?>" width="<?php it_exchange( 'email', 'header-logo-size' ); ?>" />
					<?php endif; ?>

					<?php if ( it_exchange( 'email', 'has-header-store-name' ) ): ?>
						<h1 style="color: <?php it_exchange( 'email', 'header-store-name-color' ); ?>; font-family: <?php it_exchange( 'email', 'header-store-name-font' ); ?>; font-size: <?php it_exchange( 'email', 'header-store-name-size' ); ?>px; margin: 20px 0 0 0;">
							<?php it_exchange( 'email', 'header-store-name' ); ?>
						</h1>
					<?php endif; ?>
				</td>
			</tr>
		</table>
		<!--[if mso]>
		</td></tr></table>
		</center>
		<![endif]-->
	</td>
</tr>
