<?php
/**
 * This is the default template part for the
 * password field in the super-widget-registration template
 * part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-registration/fields/details/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_super_widget_registration_fields_before_password2' ); ?>
<div class="password2">
    <?php it_exchange( 'registration', 'password2' ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_registration_fields_after_password2' ); ?>
