<?php
/**
 * The main template file for the Remove Link in
 * the items loop for content-cart template
 * part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-cart/items/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_cart_item_before_remove_element' ); ?>
<div class="it-exchange-cart-item-remove it-exchange-table-column cart-remove">
	<?php do_action( 'it_exchange_content_cart_item_begin_remove_element' ); ?>
	<div class="it-exchange-table-column-inner">
		<?php it_exchange( 'cart-item', 'remove' ); ?>
	</div>
	<?php do_action( 'it_exchange_content_cart_item_end_remove_element' ); ?>
</div>
<?php do_action( 'it_exchange_content_cart_item_after_remove_element' ); ?>