<?php
/**
 * The main template file for the Featured Image
 * element in the cart-items loop for content-cart
 * template part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-cart/items/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_cart_item_before_featured_image_element' ); ?>
<div class="it-exchange-cart-item-thumbnail it-exchange-table-column">
	<?php do_action( 'it_exchange_content_cart_item_begin_featured_image_element' ); ?>
	<div class="it-exchange-table-column-inner">
		<?php it_exchange( 'cart-item', 'featured-image' ); ?>
	</div>
	<?php do_action( 'it_exchange_content_cart_item_end_featured_image_element' ); ?>
</div>
<?php do_action( 'it_exchange_content_cart_item_after_featured_image_element' ); ?>