<?php
/**
 * This is the default template part for the line
 * item total element.
 *
 * @since 2.0.0
 * @version 2.0.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-cart/loops/ directory
 * located in your theme.
 */
?>
<div class="it-exchange-table-column it-exchange-line-item-total-column">
	<div class="it-exchange-table-column-inner">
		<?php it_exchange( 'line-item', 'total' ); ?>
	</div>
</div>
