<?php
/**
 * This is the default template part for the
 * password2 field in the content-customer
 * template part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-profile/fields/details/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_customer_fields_before_password2' ); ?>
<div class="it-exchange-customer-password2">
	<?php it_exchange( 'customer', 'password2' ); ?>
</div>
<?php do_action( 'it_exchange_content_customer_fields_after_password2' ); ?>