<?php
/**
 * This is the default template part for the
 * register detail in the super-widget-login template
 * part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-login/actions/details
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_super_widget_login_action_before_cancel' ); ?>
<div class="cancel_url">
	<?php it_exchange( 'login', 'cancel' ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_login_action_after_cancel' ); ?>
