<?php
/**
 * The transaction products loop.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/content-confirmation/loops/
 * directory located in your theme.
*/
?>

<?php if ( it_exchange( 'transaction', 'has-products' ) ) : ?>
	<div class="it-exchange-transaction-products">
		<?php while( it_exchange( 'transaction', 'products' ) ) : ?>
			<?php it_exchange_get_template_part( 'content-confirmation/details/product' ); ?>
		<?php endwhile; ?>
	</div>
<?php endif; ?>