<?php
/**
 * The transaction products loop.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/content-confirmation/loops/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_confirmation_before_products_loop' ); ?>
<?php if ( it_exchange( 'transaction', 'has-products' ) ) : ?>
	<?php do_action( 'it_exchange_content_confirmation_begin_products_loop' ); ?>
	<div class="it-exchange-transaction-products">
		<?php while( it_exchange( 'transaction', 'products' ) ) : ?>
			 <?php foreach( it_exchange_get_template_part_elements( 'content_confirmation', 'products_loop', array( 'product' ) ) as $detail ) : ?>
                <?php it_exchange_get_template_part( 'content-confirmation/elements/' . $detail ); ?>
			<?php endforeach; ?>
		<?php endwhile; ?>
	</div>
	<?php do_action( 'it_exchange_content_confirmation_end_products_loop' ); ?>
<?php endif; ?>
<?php do_action( 'it_exchange_content_confirmation_after_products_loop' ); ?>