<?php
/**
 * The transaction meta loop.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/content-confirmation/loops/
 * directory located in your theme.
*/
?>

<div class="it-exchange-transaction-meta">
	<?php do_action( 'it_exchange_content_confirmation_transaction_meta_top' ); ?>
	<?php foreach( it_exchange_get_confirmation_template_transaction_meta_elements() as $meta ) : ?>
		<?php it_exchange_get_template_part( 'content-confirmation/details/' . $meta ); ?>
	<?php endforeach; ?>
	<?php do_action( 'it_exchange_content_confirmation_transaction_meta_bottom' ); ?>
</div>