<?php
/**
 * This is the default template part for the
 * register element in the content-checkout guest-checkout purchase requirements template
 * part located in the core-addons/admin/guest-checkout/lib/templates directory
 *
 * @since CHANGEME
 * @version CHANGEME
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-checkout/elements/purchase-requirements/guest-checkout/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_checkout_guest_checkout_purchase_requirement_before_register_elements' ); ?>
<div class="register-action">
	<?php echo it_exchange_guest_checkout_get_purchase_requirement_register_action(); ?>
</div>
<?php do_action( 'it_exchange_content_checkout_guest_checkout_purchase_requirement_after_register_elements' ); ?>
