<?php
/**
 * This is the default template part for the
 * empty_cart action in the content-checkout
 * template part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-checkout/actions/ directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_checkout_actions_before_checkout_cancel' ); ?>
<div class="it-exchange-checkout_cancel">
	<?php it_exchange( 'checkout', 'cancel' ); ?>
</div>
<?php do_action( 'it_exchange_content_checkout_actions_after_checkout_cancel' ); ?>