<?php
/**
 * This is the default template part for the line
 * item quantity element.
 *
 * @since 1.36.0
 * @version 1.36.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-cart/loops/ directory
 * located in your theme.
 */
?>
<?php if ( it_exchange( 'line-item', 'supports-quantity' ) ): ?>
	<div class="it-exchange-table-column it-exchange-line-item-quantity-column">
		<div class="it-exchange-table-column-inner">
			<?php it_exchange( 'line-item', 'quantity', 'format=var_value' ); ?>
		</div>
	</div>
<?php else: ?>
	<div class="it-exchange-table-column it-exchange-column-offset" style="width: 15%;"></div>
<?php endif; ?>