<?php
/**
 * This file contains the markup for the receipt email cart totals.
 *
 * @since   1.36
 * @link    http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 *
 * Example: theme/exchange/emails/receipt/cart-totals.php
 */
?>
<tr>
	<td align="center">
		<!--[if mso]>
		<center>
			<table>
				<tr>
					<td width="640">
		<![endif]-->
		<table border="0" cellpadding="0" cellspacing="0" width="100%" style="background: <?php it_exchange( 'email', 'body-background-color' ); ?>; max-width: 640px; padding-bottom: 30px;" class="wrapper body-bkg-color">
			<tr>
				<td valign="top" style="padding: 0 25px;">
					<table width="100%" style="line-height: 1.2;">
						<?php do_action( 'it_exchange_email_template_receipt_cart-totals_before_subtotal' ); ?>
						<tr>
							<td></td>
							<td align="right" style="padding: 10px; width: 75%;">
								<strong><?php _e( 'Subtotal', 'it-l10n-ithemes-exchange' ); ?></strong>
							</td>
							<td align="right" style="padding: 10px 0 10px 10px; width: 25%;">
								<?php it_exchange( 'transaction', 'subtotal' ); ?>
							</td>
						</tr>
						<?php do_action( 'it_exchange_email_template_receipt_cart-totals_after_subtotal' ); ?>

						<?php if ( it_exchange( 'transaction', 'has-shipping-method' ) ): ?>
							<?php do_action( 'it_exchange_email_template_receipt_cart-totals_before_shipping' ); ?>
							<tr>
								<td></td>
								<td align="right" style="padding: 10px; ">
									<strong><?php _e( 'Shipping', 'it-l10n-ithemes-exchange' ); ?></strong>
								</td>
								<td align="right" style="padding: 10px 0 10px 10px; ">
									<?php it_exchange( 'transaction', 'shipping-total' ); ?>
								</td>
							</tr>
							<?php do_action( 'it_exchange_email_template_receipt_cart-totals_after_shipping' ); ?>
						<?php endif; ?>

						<?php do_action( 'it_exchange_email_template_receipt_cart-totals_before_total' ); ?>
						<tr>
							<td></td>
							<td align="right" style="padding: 10px; ">
								<strong><?php _e( 'Total', 'it-l10n-ithemes-exchange' ); ?></strong>
							</td>
							<td align="right" style="padding: 10px 0 10px 10px; ">
								<strong><?php it_exchange( 'transaction', 'total' ); ?></strong>
							</td>
						</tr>
						<?php do_action( 'it_exchange_email_template_receipt_cart-totals_after_total' ); ?>
					</table>
				</td>
			</tr>
		</table>
		<!--[if mso]>
		</td></tr></table>
		</center>
		<![endif]-->
	</td>
</tr>