<?php
/**
 * This file contains the markup for the receipt email cart details.
 *
 * @since   1.36
 * @link    http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 *
 * Example: theme/exchange/emails/receipt/cart-details.php
 */
?>
<tr>
	<td align="center">
		<!--[if mso]>
		<center>
			<table>
				<tr>
					<td width="640">
		<![endif]-->
		<table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 640px; background: <?php it_exchange( 'email', 'body-background-color' ); ?>; margin: 0 auto;" class="wrapper body-bkg-color">
			<tr>
				<td valign="top" style="padding: 20px 25px; ">
					<table width="100%" style="line-height: 1.2;">
						<tr>
							<th align="left" style="border-bottom: 1px solid <?php it_exchange( 'email', 'body-border-color' ); ?>; padding: 0 0 10px 0;" class="body-border-color"><?php _e( 'Description', 'it-l10n-ithemes-exchange' ); ?></th>
							<th align="left" style="border-bottom: 1px solid <?php it_exchange( 'email', 'body-border-color' ); ?>; padding: 0 0 10px 0;" class="body-border-color"><?php _ex( 'Qty', 'Product Quantity', 'it-l10n-ithemes-exchange' ); ?></th>
							<th align="right" style="border-bottom: 1px solid <?php it_exchange( 'email', 'body-border-color' ); ?>; padding: 0 0 10px 0;" class="body-border-color"><?php _e( 'Price', 'it-l10n-ithemes-exchange' ); ?></th>
						</tr>
						<?php while ( it_exchange( 'transaction', 'products' ) ): ?>
							<tr>
								<td align="left" style="border-bottom: 1px solid <?php it_exchange( 'email', 'body-border-color' ); ?>; padding: 10px 0;" class="body-border-color">
									<table>
										<tr>
											<?php if ( it_exchange( 'transaction', 'has-featured-image' ) ): ?>
												<td>
													<img src="<?php it_exchange( 'transaction', 'featured-image', 'format=url&size=thumbnail' ); ?>" width="80" style="margin-right: 20px;" />
												</td>
											<?php endif; ?>
											<td style="/*vertical-align: top*/">
												<strong><?php it_exchange( 'transaction', 'product-attribute', 'attribute=product_name' ); ?></strong><br>
												<?php it_exchange( 'transaction', 'variants' ); ?>
												<?php if ( it_exchange( 'transaction', 'has-purchase-message' ) ): ?>
													<p style="border-left: 4px solid <?php it_exchange( 'email', 'body-border-color' ); ?>; padding-left: 10px; max-width: 300px; font-size: .9em" class="body-border-color">
														<?php it_exchange( 'transaction', 'purchase-message' ); ?>
													</p>
												<?php endif; ?>
											</td>
										</tr>
									</table>
								</td>
								<td align="left" style="border-bottom: 1px solid <?php it_exchange( 'email', 'body-border-color' ); ?>; padding-top: 10px;" class="body-border-color">
									<?php it_exchange( 'transaction', 'product-attribute', 'attribute=product_count' ); ?>
								</td>
								<td align="right" style="border-bottom: 1px solid <?php it_exchange( 'email', 'body-border-color' ); ?>; padding-top: 10px;" class="body-border-color">
									<?php it_exchange( 'transaction', 'product-attribute', 'attribute=product_subtotal' ); ?>
								</td>
							</tr>
						<?php endwhile; ?>
					</table>
				</td>
			</tr>
		</table>
		<!--[if mso]>
		</td></tr></table>
		</center>
		<![endif]-->
	</td>
</tr>
