<?php
/**
 * This file contains the markup for the receipt email meta.
 *
 * @since   2.0.0
 * @link    http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 *
 * Example: theme/exchange/emails/receipt/meta-top.php
 */
?>
<tr>
	<td align="center">
		<!--[if mso]>
		<center>
			<table>
				<tr>
					<td width="640">
		<![endif]-->
		<table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 640px; background: <?php it_exchange( 'email', 'body-background-color' ); ?>; padding-bottom: 20px; margin: 0 auto;" class="wrapper body-bkg-color">
			<tr>
				<td valign="top" style="padding: 20px 25px; ">
					<table width="100%">
						<tr>
							<?php do_action( 'it_exchange_email_template_receipt_meta-top_begin' ); ?>

							<?php if ( it_exchange( 'transaction', 'has-billing-address' ) ): ?>
								<?php do_action( 'it_exchange_email_template_receipt_meta-top_before_billing' ); ?>
								<td style="line-height: 1.4; vertical-align: top; width: 35%;">
									<?php do_action( 'it_exchange_email_template_receipt_meta-top_begin_billing' ); ?>
									<strong><?php _e( 'Billing Address', 'it-l10n-ithemes-exchange' ); ?></strong><br>
									<?php it_exchange( 'transaction', 'billing-address' ); ?>
									<?php do_action( 'it_exchange_email_template_receipt_meta-top_end_billing' ); ?>
								</td>
								<?php do_action( 'it_exchange_email_template_receipt_meta-top_after_billing' ); ?>
							<?php endif; ?>

							<?php if ( it_exchange( 'transaction', 'has-shipping-address' ) ): ?>
								<?php do_action( 'it_exchange_email_template_receipt_meta-top_before_shipping' ); ?>
								<td style="line-height: 1.4; vertical-align: top; width: 35%">
									<?php do_action( 'it_exchange_email_template_receipt_meta-top_begin_shipping' ); ?>
									<strong><?php _e( 'Shipping Address', 'it-l10n-ithemes-exchange' ); ?></strong><br>
									<?php it_exchange( 'transaction', 'shipping-address' ); ?>
									<?php do_action( 'it_exchange_email_template_receipt_meta-top_end_shipping' ); ?>
								</td>
								<?php do_action( 'it_exchange_email_template_receipt_meta-top_after_shipping' ); ?>
							<?php endif; ?>

							<?php do_action( 'it_exchange_email_template_receipt_meta-top_before_third_block' ); ?>
							<td style="line-height: 1.1; vertical-align: top; width: 30%;">
								<?php do_action( 'it_exchange_email_template_receipt_meta-top_begin_payment_method' ); ?>
								<strong><?php _e( 'Payment Method', 'it-l10n-ithemes-exchange' ); ?></strong><br>
								<?php it_exchange( 'transaction', 'method' ); ?><br><br>
								<?php do_action( 'it_exchange_email_template_receipt_meta-top_end_payment_method' ); ?>

								<?php do_action( 'it_exchange_email_template_receipt_meta-top_begin_order_number' ); ?>
								<strong><?php _e( 'Order Number', 'it-l10n-ithemes-exchange' ); ?></strong><br>
								<?php it_exchange( 'transaction', 'order-number', array( 'label' => '%s' ) ); ?><br><br>
								<?php do_action( 'it_exchange_email_template_receipt_meta-top_end_order_number' ); ?>

								<?php do_action( 'it_exchange_email_template_receipt_meta-top_begin_parent_order' ); ?>
								<strong><?php _e( 'Parent Order', 'it-l10n-ithemes-exchange' ); ?></strong><br>
								<?php it_exchange( 'transaction', 'parent', 'label=%s' ); ?><br>
								<?php do_action( 'it_exchange_email_template_receipt_meta-top_end_parent_order' ); ?>
							</td>
							<?php do_action( 'it_exchange_email_template_receipt_meta-top_after_third_block' ); ?>

							<?php do_action( 'it_exchange_email_template_receipt_meta-top_end' ); ?>
						</tr>
					</table>
				</td>
			</tr>
		</table>
		<!--[if mso]>
		</td></tr></table>
		</center>
		<![endif]-->
	</td>
</tr>
