<?php
/**
 * This file contains the markup for the receipt email meta.
 *
 * @since   1.36
 * @link    http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 *
 * Example: theme/exchange/emails/receipt/meta-top.php
 */
?>
<tr>
	<td align="center">
		<!--[if mso]>
		<center>
			<table>
				<tr>
					<td width="640">
		<![endif]-->
		<table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 640px; background: <?php it_exchange( 'email', 'body-background-color' ); ?>; padding-bottom: 20px; margin: 0 auto;" class="wrapper body-bkg-color">
			<tr>
				<td valign="top" style="padding: 20px 25px; ">
					<table width="100%">
						<tr>
							<?php if ( it_exchange( 'transaction', 'has-billing-address' ) ): ?>
								<td style="line-height: 1.4; vertical-align: top;">
									<strong><?php _e( 'Billing Address', 'it-l10n-ithemes-exchange' ); ?></strong><br>
									<?php it_exchange( 'transaction', 'billing-address' ); ?>
								</td>
							<?php endif; ?>

							<?php if ( it_exchange( 'transaction', 'has-shipping-address' ) ): ?>
								<td style="line-height: 1.4; vertical-align: top;">
									<strong><?php _e( 'Shipping Address', 'it-l10n-ithemes-exchange' ); ?></strong><br>
									<?php it_exchange( 'transaction', 'shipping-address' ); ?>
								</td>
							<?php endif; ?>

							<td style="line-height: 1.1; vertical-align: top; ">
								<strong><?php _e( 'Payment Method', 'it-l10n-ithemes-exchange' ); ?></strong><br>
								<?php it_exchange( 'transaction', 'method' ); ?><br><br>
								<strong><?php _e( 'Order Number', 'it-l10n-ithemes-exchange' ); ?></strong><br>
								<?php it_exchange( 'transaction', 'order-number', array( 'label' => '%s' ) ); ?><br>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
		<!--[if mso]>
		</td></tr></table>
		</center>
		<![endif]-->
	</td>
</tr>