<?php
/**
 * This is the default template part for the 
 * username field in the content-registration
 * template part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-registration/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_registration_fields_before_username' ); ?>
<div class="it-exchange-registration-username">
	<?php it_exchange( 'registration', 'username' ); ?>
</div>
<?php do_action( 'it_exchange_content_registration_fields_after_username' ); ?>