<?php
/**
 * This is the default template part for the
 * nickname element in the content-customer
 * template part.
 *
 * @since CHANGEME
 * @version CHANGEME
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-profile/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_profile_before_nickname_element' ); ?>
<div class="it-exchange-customer-nickname">
	<?php it_exchange( 'customer', 'nickname' ); ?>
</div>
<?php do_action( 'it_exchange_content_profile_after_nickname_element' ); ?>