<?php
/**
 * This is the default template part for the
 * empty_cart action in the content-cart template
 * part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-cart/actions/ directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_cart_actions_before_empty_cart' ); ?>
<?php it_exchange( 'cart', 'empty' ); ?>
<?php do_action( 'it_exchange_content_cart_actions_after_empty_cart' ); ?>