<?php
/**
 * This is the default template for the 
 * super-widget-checkout update-quantity element.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-checkout/elements directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_super_widget_cart_quantity_before_wrapper' ); ?>
<div class="quantity-wrapper">
	<?php do_action( 'it_exchange_super_widget_cart_quantity_begin_wrapper' ); ?>
	<div class="quantity">
		<?php it_exchange( 'cart', 'update', 'class=it-exchange-update-quantity-button&label=' . __( 'Update Quantity', 'LION' ) ); ?>
	</div>

	<?php
	// Include the single-item-cart quantity actions template part
	it_exchange_get_template_part( 'super-widget-cart/elements/single-item-cart-cancel' );
	?>

	<?php do_action( 'it_exchange_super_widget_cart_quantity_end_wrapper' ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_cart_quantity_after_wrapper' ); ?>
