<?php
/**
 * This is the default template for the
 * super-widget-checkout customer-order-note element.
 *
 * @since 1.3.0
 * @version 1.3.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-checkout/loops directory
 * located in your theme.
 */
?>
<?php do_action( 'it_exchange_super_widget_checkout_before_customer_order_note' ); ?>
<div class="cart-customer-order-note cart-totals-row">
	<?php do_action( 'it_exchange_super_widget_checkout_begin_customer_order_note' ); ?>
	<strong><?php _e( 'Order Note:', 'it-l10n-ithemes-exchange' ); ?></strong>
	<a href="" class="it-exchange-sw-edit-customer-order-note">
		<?php _e( 'Edit', 'it-l10n-ithemes-exchange' ); ?>
	</a><br/>
	<?php echo esc_html( it_exchange_customer_order_notes_get_current_note() ); ?><br />
	<?php do_action( 'it_exchange_super_widget_checkout_end_customer_order_note' ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_checkout_after_customer_order_note' ); ?>
