<?php
/**
 * This is the default template for the
 * super-widget-shipping-address addresses loop.
 *
 * @since   2.0.0
 * @version 2.0.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-shipping-address/loops directory
 * located in your theme.
 */
?>
<?php if ( it_exchange( 'customer', 'has-addresses' ) ) : ?>
	<ul class="it-exchange-existing-addresses-selector it-exchange-existing-addresses-selector--shipping">
		<?php while ( it_exchange( 'customer', 'addresses' ) ) : ?>
			<li><?php it_exchange( 'shipping', 'radio-existing' ); ?></li>
		<?php endwhile; ?>
		<li>
			<?php it_exchange( 'shipping', 'radio-new' ); ?>
		</li>
	</ul>
<?php endif; ?>
