<?php
/**
 * This is the default template part for the
 * coupon details loop in the content-checkout
 * template part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-checkout/coupons/ directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_checkout_coupons_before_loop' ); ?>
<?php while ( it_exchange( 'coupons', 'applied', array( 'type' => 'cart' ) ) ) : ?>
	<?php do_action( 'it_exchange_content_checkout_coupons_begin_loop' ); ?>
	<div class="it-exchange-table-row">
		<?php foreach ( it_exchange_get_template_part_elements( 'content_checkout', 'coupons', array( 'coupon-code', 'coupon-discount' ) ) as $coupon_detail ) : ?>
			<?php
			/** 
			 * Theme and add-on devs should add code to this loop by 
			 * hooking into it_exchange_get_template_part_elements filter
			 * and adding the appropriate template file to their theme or add-on
			*/
			it_exchange_get_template_part( 'content-checkout/elements/' . $coupon_detail );
			?>
		<?php endforeach; ?>
	</div>
	<?php do_action( 'it_exchange_content_checkout_coupons_end_loop' ); ?>
<?php endwhile; ?>
<?php do_action( 'it_exchange_content_checkout_coupons_after_loop' ); ?>
