<?php
/**
 * This is the default template part for the
 * address2 element in the shipping-address
 * purchase-requriements in the super-widget-shipping-address template part.
 *
 * @since CHANGEME
 * @version CHANGEME
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file to the 
 * /exchange/super-widget-shipping-address/elements/
 * directory located in your theme.
*/
?>
<?php do_action( 'it_exchange_super_widget_shipping_address_purchase_requirement_before_address2_element' ); ?>
<div class="it-exchange-address2">
	<?php it_exchange( 'shipping', 'address2' ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_shipping_address_purchase_requirement_after_address2_element' ); ?>
