<?php
/**
 * This is the default template part for the
 * login element in the super-widget-guest-checkout template
 * part located in the core-addons/admin/guest-checkout/lib/templates directory
 *
 * @since CHANGEME
 * @version CHANGEME
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-guest-checkout/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_super_widget_guest_checkout_before_login_elements' ); ?>
<div class="login_url">
	<?php it_exchange( 'registration', 'cancel', array( 'label' => __( 'Log in', 'LION' ) ) ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_guest_checkoutafter_login_elements' ); ?>
