<?php
/**
 * This is the default template part for the core logged-in
 * purchase requirement element in the content-checkout
 * template part.
 *
 * @since 1.2.0
 * @version 1.2.0
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-checkout/elements/purchase-requirements directory
 * located in your theme.
*/
?>
<?php do_action( 'it_exchange_content_checkout_logged_in_purchase_requirement_before_element' ); ?>
<div class="it-exchange-checkout-logged-in-purchase-requirement">
	<?php if ( ! is_user_logged_in() ) : ?>
		<?php it_exchange_add_session_data( 'login_redirect', it_exchange_get_page_url( 'checkout' ) ); ?>
		<h3><?php _e( 'Register or Log in', 'LION' ); ?></h3>
		<div class="checkout-purchase-requirement-login-options">
			<a class="it-exchange-login-requirement-registration" href="<?php echo it_exchange_get_page_url( 'registration' ); ?>">Register</a> | 
			<a class="it-exchange-login-requirement-login" href="<?php echo it_exchange_get_page_url( 'login' ); ?>">Log in</a>
		</div>
		<div class="it-exchange-hidden checkout-purchase-requirement-login">
			<?php
			$login_loops = array( 'fields', 'actions' );
			?>
			<div class="it-exchange-login-form">
				<?php 
				do_action( 'it_exchange_content_checkout_logged_in_purchase_requirement_login_before_form' );
				it_exchange( 'login', 'form-open' );
				do_action( 'it_exchange_content_checkout_logged_in_purchase_requirement_login_begin_form' );
				// Include template parts for each of the above loops
				foreach( it_exchange_get_template_part_loops( 'content-checkout/elements/purchase-requirements/logged-in/loops/', 'login', $login_loops ) as $loop ) : 
					it_exchange_get_template_part( 'content', 'checkout/elements/purchase-requirements/logged-in/loops/login/' . $loop );
				endforeach;
				do_action( 'it_exchange_content_checkout_logged_in_purchase_requirement_login_end_form' );
				it_exchange( 'login', 'form-close' );
				?>	
			</div>
		</div>
		<div class="it-exchange-hidden checkout-purchase-requirement-registration">
			<?php
			$reg_loops = array( 'fields', 'actions' );

        	if ( it_exchange( 'registration', 'is-enabled' ) ) :
				do_action( 'it_exchange_content_checkout_logged_in_checkout_requirement_registration_before_form' );
				it_exchange( 'registration', 'form-open' );
				// Include template parts for each of the above loops
				foreach( it_exchange_get_template_part_loops( 'content-checkout/elements/purchase-requirements/logged-in/loops/', 'registration', $reg_loops ) as $loop ) : 
					it_exchange_get_template_part( 'content', 'checkout/elements/purchase-requirements/logged-in/loops/registration/' . $loop );
				endforeach;
				it_exchange( 'registration', 'form-close' );
				do_action( 'it_exchange_content_checkout_logged_in_purchase_requirement_registration_after_form' );
        	endif;
			?>	
		</div>
	<?php else : ?>
		<?php printf( __( 'Logged in as: %s', 'LION' ), it_exchange( 'customer', 'get-display-name', array( 'format' => 'field-value' ) ) ); ?> <?php wp_loginout( it_exchange_get_page_url( 'checkout' ) ); ?>
	<?php endif; ?>
</div>
<?php do_action( 'it_exchange_content_checkout_logged_in_purchase_requirement_after_element' ); ?>
