<?php
/**
 * This is the default template part for the
 * purchase requirements notification element in the content-checkout
 * template part.
 *
 * @since 1.1.3
 * @version 1.1.3
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-checkout/elements/ directory
 * located in your theme.
*/
?>

<?php if ( false !== ( $notification = it_exchange_get_next_purchase_requirement_property( 'notification' ) ) ) : ?>
	<?php do_action( 'it_exchange_content_checkout_before_purchase_requirements_notification_element' ); ?>
	<div class="it-exchange-checkout-purchase-requirements-notification">
		<?php esc_html_e( $notification ); ?>
	</div>
	<?php do_action( 'it_exchange_content_checkout_actions_after_purchase_requirements_notification_element' ); ?>
<?php endif; ?>
