<?php
/**
 * This is the default template part for the cart
 * items loop.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-checkout/loops/ directory
 * located in your theme.
*/
?>
<?php if ( is_user_logged_in() ) : ?>
	<h3><?php _e( 'Shipping Address', 'LION' ); ?></h3>
	<?php if ( it_exchange_is_shipping_address_valid() && empty( $_GET['ite-add-shipping-address'] ) ) : ?>
		<?php echo it_exchange_get_formatted_shipping_address(); ?>
		<a class="it-exchange-shipping-edit-address it-exchange-shipping-edit-existing-address" href="?ite-add-shipping-address=1" /><?php _e( 'Edit Address', 'LION' ); ?></a>
	<?php else : ?>
		<?php if ( empty( $_GET['ite-add-shipping-address'] ) ) : // Ugly little conditional for non-js hack. ?>
			<a class="it-exchange-shipping-edit-address it-exchange-shipping-add-new-address" href="?ite-add-shipping-address=1" /><?php _e( 'Add Shipping Address', 'LION' ); ?></a>
			<?php $hide_edit_address = true; ?>
		<?php endif; ?>
		<div class="it-exchange-shipping-edit-address <?php echo empty( $hide_edit_address ) ? '' : 'it-exchange-hidden'; ?>">
			<?php it_exchange_get_template_part( 'content', 'checkout/elements/purchase-requirements/shipping/edit-address' ); ?>
		</div>
	<?php endif; ?>
<?php endif; ?>
