<?php
/**
 * This is the default template part for the core shipping-method
 * purchase requirement element in the content-checkout
 * template part.
 *
 * @since CHANGEME
 * @version CHANGEME
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-checkout/elements/purchase-requirements directory
 * located in your theme.
*/

// Don't show anything if shipping-method requirement exists and hasn't been met
if ( in_array( 'customer-has-shipping-address', it_exchange_get_pending_purchase_requirements() ) )
	return;

$current_method = it_exchange_get_cart_data( 'shipping-method' );
$current_method = empty( $current_method[0] ) ? false : $current_method[0];
?>
<?php do_action( 'it_exchange_content_checkout_shipping_method_purchase_requirement_before_element' ); ?>
<div class="it-exchange-checkout-shipping-method-purchase-requirement">
	<h3><?php _e( 'Shipping Method', 'LION' ); ?></h3>
	<?php
	$methods = it_exchange_get_shipping_methods_for_cart();
	if ( count( $methods ) < 2 ) {
		$method = reset($methods);
		echo $method->label;
	} else {
		?>
		<form method="post" action="">
		<select name="it-exchange-shipping-method" onchange="this.form.submit()">
		<?php
		$options = '<option value="0">' . __( 'Select a shipping method', 'LION' );
		foreach( $methods as $method ) {
			$options .= '<option value="' . esc_attr( $method->slug ) . '" ' . selected( $current_method, $method->slug, false ) . '>' . $method->label . '</option>';
		}
		if ( (array) it_exchange_get_cart_products() > 1 )
			$options .= '<option value="multiple-methods" ' . selected( $current_method, 'multiple-methods', false ) . '>' . __( 'Use multiple shipping methods', 'LION' ) . '</option>';

		echo $options;
		?>
		</select>
		</form>
		<?php
	}
	?>
</div>
<?php do_action( 'it_exchange_content_checkout_shipping_method_purchase_requirement_after_element' ); ?>
