<?php
/**
 * This file contains the markup for the order-note activity email template.
 *
 * @since   1.36
 * @link    http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 *
 * Example: theme/exchange/emails/order-note/activity.php
 */
?>
<tr>
	<td align="center">
		<!--[if mso]>
		<center>
			<table>
				<tr>
					<td width="640">
		<![endif]-->
		<table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 640px; background: <?php it_exchange( 'email', 'body-background-color' ); ?>;" class="wrapper body-bkg-color">
			<tr>
				<td valign="top" style="padding: 0 25px;">
					<blockquote style="border-left: 5px solid <?php it_exchange( 'email', 'body-highlight-color' ); ?>; padding: 5px 0 5px 20px;">
						<?php do_action( 'it_exchange_email_template_order-note_activity_before_description' ); ?>
						<?php it_exchange( 'transaction-activity', 'description' ); ?>
						<?php do_action( 'it_exchange_email_template_order-note_activity_after_description' ); ?>

						<?php if ( it_exchange( 'transaction-activity', 'has-actor' ) ): ?>
							<p>
								<?php do_action( 'it_exchange_email_template_order-note_activity_before_cite' ); ?>
								<cite style="font-style: italic">
									<?php do_action( 'it_exchange_email_template_order-note_activity_begin_cite' ); ?>
									&mdash; <?php it_exchange( 'transaction-activity', 'actor' ); ?>
									<?php do_action( 'it_exchange_email_template_order-note_activity_end_cite' ); ?>
								</cite>
								<?php do_action( 'it_exchange_email_template_order-note_activity_after_cite' ); ?>
							</p>
						<?php endif; ?>
					</blockquote>
				</td>
			</tr>
		</table>

		<!--[if mso]>
		</td></tr></table>
		</center>
		<![endif]-->
	</td>
</tr>