<?php
/**
 * This is the default template part for the cart
 * item children loop.
 *
 * @since   1.36.0
 * @version 1.36.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-cart/loops/ directory
 * located in your theme.
 */
?>
<?php do_action( 'it_exchange_content_cart_before_item_children_loop' ); ?>
<?php while ( it_exchange( 'cart-item', 'children' ) ) : ?>
	<?php do_action( 'it_exchange_content_cart_begin_item_children_loop' ); ?>
	<?php it_exchange_get_template_part( 'content-cart/elements/item-child' ); ?>
	<?php do_action( 'it_exchange_content_cart_begin_end_loop' ); ?>
<?php endwhile; ?>
<?php do_action( 'it_exchange_content_cart_after_item_children_loop' ); ?>