<?php
/**
 * This is the default template for the 
 * super-widget-checkout discounts loop.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-checkout/loops directory
 * located in your theme.
*/
?>
<?php do_action( 'it_exchange_super_widget_checkout_before_cart_discounts' ); ?>
<div class="cart-discount">
	<?php do_action( 'it_exchange_super_widget_checkout_begin_cart_discounts' ); ?>
	<?php while( it_exchange( 'coupons', 'applied', array( 'type' => 'cart' ) ) ) : ?>
		<?php it_exchange( 'coupons', 'discount-label' ); ?> <?php _e( 'OFF', 'LION' ); ?> &#61; <?php it_exchange( 'cart', 'total' ); ?>
	<?php endwhile; ?>
	<?php do_action( 'it_exchange_super_widget_checkout_end_cart_discounts' ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_checkout_after_cart_discounts' ); ?>
