<?php
/**
 * This is the default template for the 
 * super-widget-checkout items loop.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-checkout/loops directory
 * located in your theme.
*/
?>
<?php do_action( 'it_exchange_super_widget_checkout_before_items' ); ?>
<?php do_action( 'it_exchange_super_widget_checkout_before_items_wrap' ); ?>
<div class="cart-items-wrapper">
	<?php do_action( 'it_exchange_super_widget_checkout_begin_items_wrap' ); ?>

	<?php do_action( 'it_exchange_super_widget_checkout_before_items_loop' ); ?>
	<?php while( it_exchange( 'cart', 'cart-items' ) ) : ?>
		<?php it_exchange_set_global( 'can_edit_purchase_quantity', it_exchange( 'cart-item', 'supports-purchase-quantity' ) && ( it_exchange_get_cart_products_count() < 2 ) ); ?>
		<?php do_action( 'it_exchange_super_widget_checkout_begin_items_loop' ); ?>

		<?php it_exchange_get_template_part( 'super-widget-checkout/elements/item' ); ?>
        
		<?php do_action( 'it_exchange_super_widget_checkout_end_items_loop' ); ?>
	<?php endwhile; ?>
	<?php do_action( 'it_exchange_super_widget_checkout_after_items_loop' ); ?>

	<?php 
	if ( it_exchange( 'coupons', 'has-applied', array( 'type' => 'cart' ) ) )
		it_exchange_get_template_part( 'super-widget-checkout/loops/discounts' );
	?>

	<?php do_action( 'it_exchange_super_widget_checkout_end_items_wrap' ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_checkout_after_items_wrap' ); ?>
<?php do_action( 'it_exchange_super_widget_checkout_after_items' ); ?>
