<?php
/**
 * This is the default template for the 
 * super-widget-checkout simple-shipping-cost element.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-checkout/elements directory
 * located in your theme.
*/
?>
<?php do_action( 'it_exchange_super_widget_checkout_before_simple_shipping_cost_element' ); ?>
<div class="cart-simple-shipping-cost cart-totals-row">
	<?php do_action( 'it_exchange_super_widget_checkout_begin_simple_shipping_cost_element' ); ?>
	<?php _e( 'Shipping:', 'LION' ); ?> <?php esc_attr_e( it_exchange_addon_get_simple_shipping_for_cart() ); ?>
	<?php do_action( 'it_exchange_super_widget_checkout_end_simple_shipping_cost_element' ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_checkout_after_simple_shipping_cost_element' ); ?>
