<?php
/**
 * This is the default template for the 
 * super-widget-checkout shipping address element.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-checkout/elements directory
 * located in your theme.
*/
?>
<?php do_action( 'it_exchange_super_widget_checkout_before_shipping_address_element' ); ?>
<div class="cart-shipping-address cart-totals-row">
	<?php do_action( 'it_exchange_super_widget_checkout_begin_shipping_address_element' ); ?>
	<?php _e( 'Shipping to', 'LION' ); ?><br />
	<?php echo it_exchange_get_formatted_shipping_address(); ?>
	<a href="" class="update-shipping-address"><?php _e( 'Edit', 'LION' ); ?></a>
	<?php do_action( 'it_exchange_super_widget_checkout_end_shipping_address_element' ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_checkout_after_shipping_address_element' ); ?>
