<?php
/**
 * This is the default template for the 
 * super-widget-checkout transaction-methods loop.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-checkout/loops directory
 * located in your theme.
*/
?>
<div class="payment-methods-wrapper">
	<?php if ( ! it_exchange( 'checkout', 'has-transaction-methods' ) ) : ?>
		<p><?php _e( 'No payment add-ons enabled.', 'LION' ); ?></p>
	<?php else : ?>
		<?php while( it_exchange( 'checkout', 'transaction-methods' ) ) : ?>
			<?php it_exchange( 'transaction-method', 'make-payment' ); ?>
		<?php endwhile; ?>
	<?php endif; ?>
</div>
