<?php
/**
 * This is the default template part for the cart
 * items loop.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-checkout/loops/ directory
 * located in your theme.
*/
?>
<form action="<?php echo it_exchange_get_page_url( 'checkout' ); ?>" method="post" />
	<?php _e( 'Name', 'LION' ); ?><br />
	<input type="text" class="it-exchange-addon-simple-shipping-name" name="it-exchange-addon-simple-shipping-name" <?php it_exchange_addon_simple_shipping_address_value( 'name' ); ?>/><br />
	<?php _e( 'Address', 'LION' ); ?><br />
	<input type="text" class="it-exchange-addon-simple-shipping-address-1" name="it-exchange-addon-simple-shipping-address-1" <?php it_exchange_addon_simple_shipping_address_value( 'address1' ); ?>/><br />
	<input type="text" class="it-exchange-addon-simple-shipping-address-2" name="it-exchange-addon-simple-shipping-address-2" <?php it_exchange_addon_simple_shipping_address_value( 'address2' ); ?>/><br />
	<?php _e( 'City', 'LION' ); ?><br />
	<input type="text" class="it-exchange-addon-simple-shipping-city" name="it-exchange-addon-simple-shipping-city" <?php it_exchange_addon_simple_shipping_address_value( 'city' ); ?>/><br />
	<?php _e( 'State', 'LION' ); ?> <?php _e( 'Zip', 'LION' ); ?><br />
	<input type="text" class="it-exchange-addon-simple-shipping-state" name="it-exchange-addon-simple-shipping-state" <?php it_exchange_addon_simple_shipping_address_value( 'state' ); ?>/> 
	<input type="text" class="it-exchange-addon-simple-shipping-zip" name="it-exchange-addon-simple-shipping-zip" <?php it_exchange_addon_simple_shipping_address_value( 'zip' ); ?>/><br />
	<?php _e( 'Country', 'LION' ); ?><br />
	<input type="text" class="it-exchange-addon-simple-shipping-country" name="it-exchange-addon-simple-shipping-country" <?php it_exchange_addon_simple_shipping_address_value( 'country' ); ?>/><br />
	<input type="hidden" name="it-exchange-simple-shipping-add-address-from-checkout" value="1" />
	<input type="submit" value="<?php esc_attr_e( __( 'Save', 'LION' ) ); ?>" />
	<a class="it-exchange-simple-shipping-cancel-address-update" href="<?php echo it_exchange_get_page_url( 'checkout' ); ?>"><?php _e( 'Cancel', 'LION' ); ?></a>
</form>
