<?php
/**
 * Default template for displaying a customer
 * downloads.
 * 
 * @since 0.4.0
 * @version 1.0.2
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 * 
 * Example: theme/exchange/content-downloads.php
*/
?>

<div id="it-exchange-downloads" class="it-exchange-wrap it-exchange-account">
	<?php it_exchange_get_template_part( 'messages' ); ?>
	<?php it_exchange( 'customer', 'menu' ); ?>
	<?php it_exchange_get_template_part( 'content-downloads/loops/transaction-loop' ); ?>
</div>
