<?php
/**
 * Default template for displaying the a single
 * exchange product.
 * 
 * @since 0.4.0
 * @version 1.0.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 * 
 * Example: theme/exchange/content-product.php
*/
?>

<?php it_exchange_get_template_part( 'messages' ); ?>

<?php do_action( 'it_exchange_content_product_before_product' ); ?>
<div id="it-exchange-product">
	<?php do_action( 'it_exchange_content_product_begin_product' ); ?>
	<div class="product-standard-content product-columns <?php echo ( it_exchange( 'product', 'has-images' ) ) ? ' has-images' : ''; ?>">
		<div class="product-column product-info">
			<div class="product-column-inner">
				<?php it_exchange_get_template_part( 'content-product/loops/product-info' ); ?>
			</div>
		</div>
		<?php it_exchange_get_template_part( 'content-product/loops/product-images' ); ?>
	</div>
	
	<div class="product-advanced-items">
		<?php it_exchange_get_template_part( 'content-product/loops/product-advanced' ); ?>
	</div>
	<?php do_action( 'it_exchange_content_product_end_product' ); ?>
</div>
<?php do_action( 'it_exchange_content_product_after_product' ); ?>
