<?php
/**
 * Default template part for the cart page.
 * 
 * @since 0.4.0
 * @version 1.0.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates* @updated 1.0.0
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 * 
 * Example: theme/exchange/content-cart.php
*/
?>

<div id="it-exchange-cart" class="it-exchange-wrap">
	<?php it_exchange_get_template_part( 'messages' ); ?>
	
	<?php if ( it_exchange( 'cart', 'has-cart-items' ) ) :  ?>
		<?php do_action( 'it_exchange_cart_start' ); ?>
			<?php it_exchange( 'cart', 'form-open' ); ?>
			
			<?php do_action( 'it_exchange_cart_form_top' ); ?>
				
				<?php do_action( 'it_exchange_cart_items_start' ); ?>
					<div id="it-exchange-cart-items" class="it-exchange-table">
						<?php it_exchange_get_template_part( 'cart/items/loop' ); ?>
					</div>
				<?php do_action( 'it_exchange_cart_items_end' ); ?>
				
				<?php do_action( 'it_exchange_cart_coupons_start' ); ?>
					<div id="it-exchange-cart-coupons" class="it-exchange-table">
						<?php it_exchange_get_template_part( 'cart/coupons/loop' ); ?>
					</div>
				<?php do_action( 'it_exchange_cart_coupons_end' ); ?>
				
				<?php do_action( 'it_exchange_cart_totals_start' ); ?>
					<div id="it-exchange-cart-totals" class="it-exchange-table">
						<?php it_exchange_get_template_part( 'cart/totals/loop' ); ?>
					</div>
				<?php do_action( 'it_exchange_cart_totals_end' ); ?>
				
				<?php do_action( 'it_exchange_cart_actions_start' ); ?>
					<div id="it-exchange-cart-actions">
						<?php foreach( it_exchange_get_cart_actions() as $action ) : ?>
							<?php it_exchange_get_template_part( 'cart/actions/' . $action ); ?>
						<?php endforeach; ?>
					</div>
				<?php do_action( 'it_exchange_cart_actions_end' ); ?>
			
			<?php do_action( 'it_exchnage_cart_form_bottom' ); ?>
			
			<?php it_exchange( 'cart', 'form-close' ); ?>
		<?php do_action( 'it_exchange_cart_end' ); ?>
	<?php else : ?>
		<?php do_action( 'it_exchange_empty_cart_start' ); ?>
			<p><?php _e( 'There are no items in your cart', 'LION' ); ?></p>
		<?php do_action( 'it_exchange_empty_cart_end' ); ?>
	<?php endif; ?>
</div>