<?php
/**
 * Default template part for the purchase
 * confirmation page.
 * 
 * @since 0.4.0
 * @version 1.0.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 * 
 * Example: theme/exchange/content-confirmation.php
*/
?>
<?php do_action( 'it_exchange_confirmation_template_part_top' ); ?>
<div id="it-exchange-confirmation">
	<?php if ( it_exchange( 'transactions', 'found' ) ) : ?>
		<?php while( it_exchange( 'transactions', 'exist' ) ) : ?>

			<?php it_exchange_get_template_part( 'confirmation/transaction-meta' ); ?>
			
			<?php if ( it_exchange( 'transaction', 'has-products' ) ) : ?>
				<div class="transaction-products">
					<?php while( it_exchange( 'transaction', 'products' ) ) : ?>
						<?php it_exchange_get_template_part( 'confirmation/transaction-product' ); ?>
					<?php endwhile; ?>
				</div>
			<?php endif; ?>
		<?php endwhile; ?>
	<?php else : ?>
		<?php it_exchange_get_template_part( 'confirmation/no-transaction-found' ); ?>
	<?php endif; ?>
</div>
<?php do_action( 'it_exchange_confirmation_template_part_bottom' ); ?>
