<?php
/**
 * Default template for displaying the an exchange
 * customer's purchase(s).
 * 
 * @since 0.4.0
 * @version 1.0.1
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 * 
 * Example: theme/exchange/content-purchases.php
*/
?>

<?php it_exchange_get_template_part( 'messages' ); ?>

<div id="it-exchange-purchases" class="it-exchange-wrap it-exchange-account">

	<?php it_exchange( 'customer', 'menu' ); ?>

	<?php do_action( 'it_exchange_content_purchases_fields_before_loop' ); ?>

	<?php 
	// Loop through transactions
	if ( it_exchange( 'transactions', 'found' ) )
		it_exchange_get_template_part( 'content-purchases/loops/transactions' );
	else
		it_exchange_get_template_part( 'content-purchases/no-purchases-notice' );

	do_action( 'it_exchange_content_purchases_fields_after_loop' ); ?>
</div>
