<?php
/**
 * This file contains the markup for the email template.
 *
 * @since   1.36
 * @link    http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 *
 * Example: theme/exchange/email.php
 */
?>

<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Test</title>
</head>
<body>

<span class="email-text-color">This is just filer to get things working.</span>

<!-- o:Background -->

<!-- o:Header -->

<!-- Header Image -->

<!-- Header Logo -->

<!-- c:Header -->


<!-- o:Content -->

<!-- c:Content -->


<!-- o:Footer -->

<!-- c:Footer -->

<!-- c:Background -->

<?php if ( is_customize_preview() ) {
	wp_footer();
} ?>
</body>
</html>