<?php
/**
 * This is the default template part for a
 * product in the store.
 * 
 * @since 0.4.0
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 * 
 * Example: theme/exchange/store-product.php
*/
?>

<?php it_exchange( 'product', 'permalink', 'format=html' ); ?>
