<?php
/**
 * This is the default template part for a
 * product in the store.
 * 
 * @since 0.4.0
 * @version 1.0.2
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
*/
?>

<?php do_action( 'it_exchange_store_product_before_product' ); ?>
<li class="it-exchange-product">
	<?php do_action( 'it_exchange_store_product_begin_product' ); ?>
	<?php it_exchange_get_template_part( 'store-product/loops/product-images' ); ?>
	<div class="it-exchange-product-details">
		<?php it_exchange_get_template_part( 'store-product/loops/product-info' ); ?>
	</div>
	<?php do_action( 'it_exchange_store_product_end_product' ); ?>
</li>
<?php do_action( 'it_exchange_store_product_after_product' ); ?>