<?php
/**
 * The checkout template for the Super Widget.
 * 
 * @since 0.4.0
 * @version 1.0.1
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 * 
 * Example: theme/exchange/super-widget-checkout.php
*/
?>

<?php it_exchange_get_template_part( 'messages' ); ?>

<div class="it-exchange-sw-processing it-exchange-sw-processing-checkout">
	<?php
	// If we have cart Items
	if ( it_exchange( 'cart', 'has-cart-items' ) ) {
		// Loop through cart items
		it_exchange_get_template_part( 'super-widget-checkout/loops/items' );

		// Loop through payment options if allowed
		if ( ! it_exchange_is_multi_item_cart_allowed() || ( it_exchange_is_multi_item_cart_allowed() && it_exchange_get_cart_products_count() < 2 ) )
			it_exchange_get_template_part( 'super-widget-checkout/loops/transaction-methods' );

		// Show checkout actions
		if ( ( it_exchange( 'coupons', 'accepting', array( 'type' => 'cart' ) ) || it_exchange( 'coupons', 'has-applied', array( 'type' => 'cart' ) ) ) || it_exchange_get_global( 'can_edit_purchase_quantity' ) )
			it_exchange_get_template_part( 'super-widget-checkout/loops/actions' ); 
	
	} else {
		it_exchange_get_template_part( 'super-widget-cart/elements/empty-cart-notice' );
	}
	?>
</div>
