<?php
/**
 * This is the default template for the
 * content-login fields loop.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-login/loops directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_chekcout_purchase_requirement_logged_in_before_login_fields_loop' ); ?>
<?php foreach( it_exchange_get_template_part_elements( 'content_checkout/elements/purchase-requirements/logged-in/elements/login/', 'fields', array( 'username', 'password', 'rememberme' ) ) as $field ) : ?>
	<?php
	/**
	 * Theme and add-on devs should add code to this loop by 
	 * hooking into it_exchange_get_template_part_elements filter
	 * and adding the appropriate template file to their theme or add-on
	 */
	it_exchange_get_template_part( 'content', 'checkout/elements/purchase-requirements/logged-in/elements/login/' . $field );
	?>
<?php endforeach; ?>
<?php do_action( 'it_exchange_content_chekcout_purchase_requirement_logged_in_after_login_fields_loop' ); ?>
