<?php
/**
 * This is the default template part for the
 * no-products-found message in the content-store template part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-cart/coupons/ directory
 * located in your theme.
*/
?>
<p>
	<?php _e( 'No Products Found', 'LION' ); ?>
</p>
